language: cpp
sudo: required
services:
  - docker
install:
  #- wget http://downloads.conan.io/latest_debian -O conan.deb
  - wget https://s3-eu-west-1.amazonaws.com/downloads.conan.io/conan-dev.deb -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb
  - conan user # It creates the conan data directory
script:
- export CONAN_UPLOAD=1 && python build_with_docker.py