language: cpp
sudo: required
services:
  - docker
install:
  - wget http://downloads.conan.io/latest_debian -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb
  - conan user # It creates the conan data directory
script:
- export CONAN_UPLOAD=1 && python build_with_docker.py