language: python
sudo: required
services:
  - docker
env:
  - GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=1
  - GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=2
  - GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=3
  - GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=4
  
  - GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=1
  - GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=2
  - GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=3
  - GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=4
  
  - GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=1
  - GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=2
  - GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=3
  - GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=4
  
  - GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=1
  - GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=2
  - GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=3
  - GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=4
  
  - GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=1
  - GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=2
  - GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=3
  - GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=4

install:
  - pip install conan_build_tools # It install conan too
  - conan user # It creates the conan data directory
script:
  - export CONAN_UPLOAD=1 && 
    export CONAN_REFERENCE="OpenSSL/1.0.2e" && 
    export CONAN_USERNAME="lasote" && 
    export CONAN_CHANNEL="travis" && 
    export CONAN_TOTAL_PAGES=4 && 
    python build_with_docker.py
