language: cpp
sudo: required
services:
  - docker
env:
  - GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 4.6 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 4.8 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 4.9 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 5.2 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
  - GCC_VERSIONS: 5.3 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2

install:
  - wget http://downloads.conan.io/latest_debian -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb
  - conan user # It creates the conan data directory
script:
  - export CONAN_UPLOAD=1 && 
    export CONAN_REFERENCE="OpenSSL/1.0.2e" && 
    export CONAN_USERNAME="lasote" && 
    export CONAN_CHANNEL="travis" && 
    python build_with_docker.py
